### ISSUE TITLE
broken layout in SKOS documentation

### ISSUE THREAD

**Issue by VladimirAlexiev** [Interoperable-data/ERA-Ontology-3.1.0#103]
https://linkedvocabs.org/data/era-ontology/3.1.0/doc/resources/skos/ : the column layout is broken when scheme names are too long. See red below:
![image](https://github.com/user-attachments/assets/d01613a7-4d90-41d1-b118-e27161506d6a)

**Comment by gatemezing** [comment]
Dear @VladimirAlexiev  - just started the work last night :) - Work in progress for integration in the next days

**Comment by gatemezing** [comment]
Solved in the new version - thank you!
