### ISSUE TITLE
Missing definition/reference: Primary Location

### ISSUE THREAD

**Issue by gdschut** [Interoperable-data/ERA-Ontology-3.1.0#17]
It seems Primary Location means "PLC" as used in TSI TAF/TAP (Telemetics soon), but it lacks a proper definition/link to this concept.

Proposal: Refer to Sector Handbook definition:

**Definition of Primary Location**

> Primary Location is a place used by IM to define a path for a train in TAF/TAP TSI
> framework/messages. This location is a rail point inside the rail network where train starts,
> ends, stops, or runs through or change line. This location must be managed by an
> Infrastructure Manager (IM) identified by company code.
> Primary locations are for example: stations, yards, halts, handover points, border points,
> open access terminals.
> Primary locations are identified by single and unique Primary Location codes. Primary
> location code is allocated based on processes defined by national entity. Primary location
> codes are used in any kind of TAF/TAP communication.

http://taf-jsg.info/wp-content/uploads/2024/01/20231018-JGS-Handbook-3.4-with-XSD-3.4.0.0.pdf
9.3.3 / page 60

**Comment by Interoperable-data** [comment]
Thank you Gerben for your contribution. 
The definition was added along with a reference to the TAF and TAP TSIs sector handbook
