### ISSUE TITLE
Missing definition: Aggregated Object

### ISSUE THREAD

**Issue by gdschut** [Interoperable-data/ERA-Ontology-3.1.0#18]
https://linkedvocabs.org/data/era-ontology/3.1.0/doc/index-en.html#AggregatedObject misses a definition.
It was called "meso"(ish) before, but renaming an objecttype does not clarify the meaning.

Looking at the name "aggregated", which means:
a whole formed by combining several separate elements.
"the council was an aggregate of three regional assemblies"

It is unclear to me why the RBC should be a subtype of Aggregated Object.

But looking at https://linkedvocabs.org/data/era-ontology/3.1.0/doc/index-en.html#RadioBlockCenter, it misses also a clear definition, so it could be anything, so perhaps it is true indeed...

Pleas add ALL definitions first!!!

**Comment by Interoperable-data** [comment]
Definitions are added to the ontology and the documentation will be updated
