### ISSUE TITLE
remove empty prefix and base

### ISSUE THREAD

**Issue by VladimirAlexiev** [Interoperable-data/ERA-Ontology-3.1.0#42]
Remove these lines:
```ttl
@prefix : <http://data.europa.eu/949/> .
@base <http://data.europa.eu/949/> .
```
Using empty prefix or relative URLs in ontologies is imho not a good practice.
AFAIK, they are not used.
So remove them.

**Comment by Interoperable-data** [comment]
Thank you! fixed
