### ISSUE TITLE
define and use prefixes for all external terms

### ISSUE THREAD

**Issue by VladimirAlexiev** [Interoperable-data/ERA-Ontology-3.1.0#43]
Everytime I see a long class/prop URL, I start having doubts whether it's a correct one.

So define and use the following prefixes:
```ttl
@prefix geo: <http://www.opengis.net/ont/geosparql#>.
@prefix cc: <http://creativecommons.org/ns#>.
@prefix org:  <http://www.w3.org/ns/org#>.
@prefix vs: <http://www.w3.org/2003/06/sw-vocab-status/ns#>.
@prefix dc: <http://purl.org/dc/elements/1.1/>.
@prefix wgs: <http://www.w3.org/2003/01/geo/wgs84_pos#>.
```

You can also
```ttl
# REPLACE
<http://data.europa.eu/949/> rdf:type owl:Ontology ;
...
rdfs:isDefinedBy <http://data.europa.eu/949/>;

# BY
era: rdf:type owl:Ontology ;
...
rdfs:isDefinedBy era: ;
```
to emphasize that it's the same URL as the prefix (a prefixed name with empty localname is perfectly valid)

**Comment by Interoperable-data** [comment]
Thank you for the comment. Is there any issue when consuming the ontology in its current state?

**Comment by VladimirAlexiev** [comment]
There's no issue with machine-readability, but there is an issue with human readability.
You use a prefix `era`: by the same token prefixes for all external terms referenced are also useful.

**Comment by Interoperable-data** [comment]
Since the semantics is preserved for machines (say machine readable), we will not control the output of Protégé in terms of using exactly your suggestion.

**Comment by Interoperable-data** [comment]
Thank you! we'll keep that in mind.
