### ISSUE TITLE
LODE: improve name of `inSkosConceptScheme`

### ISSUE THREAD

**Issue by VladimirAlexiev** [Interoperable-data/ERA-Ontology-3.1.0#54]
https://github.com/Interoperable-data/ERA_vocabulary/issues/20 shows that:
`inSkosConceptScheme` has label "in SKOS Concept Scheme" but is rendered in the ontology documentation as "In Scope Concept Scheme".

The latter (current) displayed label is inaccurate/misleading. Please change it to "Values from SKOS Concept Scheme".

**Comment by Interoperable-data** [comment]
Fixed here https://linkedvocabs.org/data/era-ontology/3.1.0/doc/index-en.html#profileNumberSwapBodies
