### ISSUE TITLE
replace `dct:requires` with an textual prop

### ISSUE THREAD

**Issue by VladimirAlexiev** [Interoperable-data/ERA-Ontology-3.1.0#58]
```ttl
era:atoCommunicationSystem rdf:type owl:ObjectProperty ;
                           rdfs:domain era:CCSSubsystem ;
                           rdfs:range <http://www.w3.org/2004/02/skos/core#Concept> ;
                           era:inSkosConceptScheme <http://data.europa.eu/949/concepts/ato-commsys/ATOCommSystem> ;
                           dcterms:relation era:etcsBaseline ;
                           dcterms:requires "Parameter only applicable when ETCS Baseline > 4 MR1 and ATO is implemented" ;
```
- `dct:requires` is defined as  "A related **resource** that is required by the described resource to support its function, delivery, or coherence". So it cannot be a text
- `dct:relation` is pretty generic and doesn't express the nature of the relation.

So I suggest to replace this with:
```ttl
  dcterms:requires era:etcsBaseline ;
  skos:scopeNote"Parameter only applicable when ETCS Baseline > 4 MR1 and ATO is implemented" ;
```

Same applies to `era:atoGradeAutomation, era:atoSystemVersion`

**Comment by Interoperable-data** [comment]
[(`dcterms:relation `) ](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http%3a%2f%2fpurl.org%2fdc%2fterms%2frelation)does require a URI, in the namespace `/dc/elements/1.1/` (not the one in /  "Recommended practice is to identify the **related resource by means of a URI.** If this is not possible or feasible, a string conforming to a formal identification system may be provided".
+1 of using skos:scopeNote for the precision of the usage, that will be enforces in a SHACL rule
