### ISSUE TITLE
remove rdfs:Literal

### ISSUE THREAD

**Issue by VladimirAlexiev** [Interoperable-data/ERA-Ontology-3.1.0#68]
rdfs:Literal is a very unspecific datatype and shouldn't be used.

Remove it from the first `rinfIndex` value here:
```ttl
era:frenchTrainDetectionSystemLimitationApplicable rdf:type owl:DatatypeProperty ;
                                                   era:rinfIndex "1.2.1.1.6.3"^^rdfs:Literal ,
                                                                 "1.1.1.3.7.1.4" ;
```

(Note to self: it's also used as range of `foaf:name, dcterms:identifier` but that comes from the original ontologies, so can be left alone)

**Comment by Interoperable-data** [comment]
Yes, it is also to be consistent with the rest of the values for this annotation property

**Comment by Interoperable-data** [comment]
Done, thanks!
