### ISSUE TITLE
change range ConceptScheme to Concept plus  inSkosConceptScheme

### ISSUE THREAD

**Issue by VladimirAlexiev** [Interoperable-data/ERA-Ontology-3.1.0#69]
The props `era:side era:orientation era:lrsMethod era:direction` have range `skos:ConceptScheme`.
I think this is a mistake.
Like all other SKOS-valued props, they should have range `skos:Concept`, plus a reference `era:inSkosConceptScheme`

**Comment by Interoperable-data** [comment]
fixed!

**Comment by VladimirAlexiev** [comment]
Now only `era:inSkosConceptScheme` has `rdfs:range skos:ConceptScheme`: good!
